// export const GET_AUTH = 'GET_AUTH'
// export const ADD_LOCATION = 'ADD_LOCATION'
// export const NEW_LOCATION = 'NEW_LOCATION'
// export const LOAD_LOCATION = 'LOAD_LOCATION'
// export const GET_LOCATIONS = 'GET_LOCATIONS'
// export const UPDATE_LOCATION = 'UPDATE_LOCATION'
// export const REMOVE_LOCATION = 'REMOVE_LOCATION'